FROM node:18-slim

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

ENV PATH=$PATH:/home/node/.npm-global/bin

RUN mkdir -p /app

# nc(netcat) 커맨드 설치
RUN apt update && apt install netcat -y && apt install openssl -y

RUN chown --changes --silent --no-dereference --recursive \
    node:node /app

USER node

RUN npm install -g nodemon

WORKDIR /app

COPY --chown=node:node package.json .

RUN npm install

COPY --chown=node:node prisma ./prisma/

RUN npx prisma generate

COPY --chown=node:node . .

CMD ["npm", "run", "start"]